### ISSUE TITLE
Collaborate

### ISSUE THREAD

**Issue by timkpaine** [lydian/multicontents#3]
Just wondering if you'd like to collaborate. 
https://github.com/timkpaine/multicontentsmanager

**Comment by lydian** [comment]
@timkpaine that sounds good, do you have any idea how you want to collaborate?

**Comment by timkpaine** [comment]
@lydian we're in the progress of cleaning up and consolidating what we have, we are going to move it to the sponsoring organization. Once its there, it would be awesome if you could help us see what works and what doesn't, since you're familiar with the ugliness of the current Jupyter contents API you can probably help us fix it :-)

this project is going to be sponsored and involve contributions from core Jupyter maintainers, so it will be good to get any interested people involved.

**Comment by timkpaine** [comment]
https://github.com/jpmorganchase/jupyter-fs
